### ISSUE TITLE
[MISC] Items and Feature that increase range of Darkvision

### ISSUE THREAD

**Issue by NickVendel** [AuroraLegacy/elements#118]
**_Umbral Sight_** feature of Gloom Stalker Ranger and some items extend range of Darkvision if you already have it by the time you gain feature, equip, or attune to the item. 
Currently those don't do that, and we recommend to use Additional Features that increase range of visions to fix that.

**Comment by kgirtxd** [comment]
This will require something like the proficiency or double concept
