### ISSUE TITLE
[WDMM] Werebat Lycanthropy

### ISSUE THREAD

**Issue by FreshRoyal** [AuroraLegacy/elements#131]
The werebat from Waterdeep: Dungeon of the Mad Mage is currently missing. 5e.tools link below.

- https://5e.tools/bestiary.html#werebat_wdmm

**Comment by kgirtxd** [comment]
WDMM pg 317

**Werebat Lycanthropy.** A player character who becomes a werebat gains a Dexterity of17 if their score isn't already higher. Attack and damage rolls for the werebat's bite attack are based on the character's Strength or Dexterity score, whichever is higher.
