### ISSUE TITLE
Artificer Infusions inconsistent labeling

### ISSUE THREAD

**Issue by ErrantFamiliar** [AuroraLegacy/elements#166]
Artificer Infusions labeling under 'Rarity' is inconsistent and sometimes downright incorrect. 
Some are labeled as Artificer Infusions, and others aren't labeled. The most problematic are the Arcane Propulsion Armor, and Armor of Magical Strength which are labeled as Common magic items. The information in the description doesn't call them out as Artificer Infusions either.

**Comment by NickVendel** [comment]
@ErrantFamiliar on a separate note, do you have a discord account?

**Comment by ErrantFamiliar** [comment]
@NickVendel Indeed I do, I can be found as Illicit Eggplant#0453
