### ISSUE TITLE
Multiple races not working

### ISSUE THREAD

**Issue by DDBBAA119** [AuroraLegacy/elements#171]
Many of the "Monsters of the multiverse" and "Fizban's treasury of Dragons" races do not work. It is impossible to take feats they normally should have, and an error messages appear when creating them, or doing anything while the character is open. If a character is still created Aurora cannot launch the character afterwards.  

Example Eladrin "Monsters of the multiverse" when selecting this race, this error message pops up 

![oo1](https://user-images.githubusercontent.com/110948961/183789512-628145d8-15f5-46f4-aa54-4ec2e2349c4d.png)

**Comment by kgirtxd** [comment]
@DDBBAA119 if you look at the Read ME
![image](https://user-images.githubusercontent.com/15676362/183789900-b066ebf9-453a-4169-b7fd-900bcd9bf046.png)

**Comment by DDBBAA119** [comment]
Oh I'm sorry, but thank you for pointing that out.

**Comment by kgirtxd** [comment]
no probs
