### ISSUE TITLE
Tasha's Cauldren of Everything

### ISSUE THREAD

**Issue by aurorabuilderlegacy** [AuroraLegacy/elements#19]
Part 1:  Done in #8 
- [x] Class Archetypes
- [x] Feats
- [x] Spells
- [x] Items
- [x] Fighting Styles
- [x] Invocations
- [x] Maneuvers
- [x] Metamagics
- - - 

Part 2: Done in #20 
- [x] Race Revamp
- [x] Custom Lineage 

- - - 

Part 3: Done in #41 
- [x] Optional Class Features
- [x] Extended Spell Lists
- [x] Missing Artificer Infusions

**Comment by nkolbe1** [comment]
How do I access the code to add it to Aurora?

**Comment by kgirtxd** [comment]
@nkolbe1  https://github.com/AuroraLegacy/elements/blob/master/README.md

**Comment by Mr-mask6767** [comment]
Is there any way to assist in getting optional class features and spell lists up and running? or are we just waiting on review?

**Comment by kgirtxd** [comment]
Currently we are waiting for @NickVendel to update the pull based of community feedback.  Once done we will continue the review process.  If you would like to review the pull and post bugs, that can speed things along to an extent.

**Comment by aurorabuilderlegacy** [comment]
TCoE Complete
