### ISSUE TITLE
Dhampir race causing crashes

### ISSUE THREAD

**Issue by HomosexualBeanbag** [AuroraLegacy/elements#195]
**Describe the issue**
When making a Dhampir character, any time I edit anything I get an error "Unable to find ID_INTERNAL_RACIAL_TRAIT_TYPE_HUMANOID of type Racial Trait that was set as grand in Dhampir (Race)."
This error pops up repeatedly when trying to progress, and when trying to de-level my character, it pops up, and when closed, crashes the entire client.
**Additional context**
I have just recently updated to windows 11, but this problem started on windows 10. All other characters and races work fine.
![image](https://user-images.githubusercontent.com/126113027/220747601-5a18e3f6-755f-4ecc-a9ae-94b3ca35d7da.png)

**Comment by kgirtxd** [comment]
#171
