### ISSUE TITLE
Custom lineage ASI doesn't work

### ISSUE THREAD

**Issue by kuro2629** [AuroraLegacy/elements#57]
When clicking on "Ability Score Improvement +2 (custom lineage)" there is no menu to choose the ability score to improve, even if the "customized ability score increases" character option is selected
Same problem is present when using the gothic lineages (dhampir, reborn and hexblood)

**Comment by AngryGuineaPig** [comment]
The system does work, the selection can be found in the Ability Score tab

**Comment by kgirtxd** [comment]
@kuro2629 can you post screenshots of your issue?  We are unable to replicate it.

**Comment by Jweb123** [comment]
I am also having the same/similar issue. The racial ASI shows up in the ability score menu, but there is no dropdown to select which ability to increase. My issue was occurring with aasimar using customized ability scores.
![Screenshot (18)](https://user-images.githubusercontent.com/79847344/109497376-f53f9a00-7a5f-11eb-9aa7-e00898412296.png)

![Screenshot (19)](https://user-images.githubusercontent.com/79847344/109497272-c9bcaf80-7a5f-11eb-990a-f011679be95c.png)

**Comment by AngryGuineaPig** [comment]
> I am also having the same/similar issue. The racial ASI shows up in the ability score menu, but there is no dropdown to select which ability to increase. My issue was occurring with aasimar using customized ability scores.
> ![Screenshot (18)](https://user-images.githubusercontent.com/79847344/109497376-f53f9a00-7a5f-11eb-9aa7-e00898412296.png)
> 
> ![Screenshot (19)](https://user-images.githubusercontent.com/79847344/109497272-c9bcaf80-7a5f-11eb-990a-f011679be95c.png)

I've tried to recreate this issue but it's all working for me, artificer asi increase and protector aasimar
![image](https://user-images.githubusercontent.com/73967795/109558871-d974dc00-7ad1-11eb-877b-eefcbbf617db.png)

**Comment by kgirtxd** [comment]
@Jweb123 @kuro2629 Make sure you are using our core.index there are things we added there that are required for some features to work.

**Comment by Jweb123** [comment]
@kgirtxd That fixed it for me, feel like an idiot but I'm glad it was just user error on my part.

**Comment by NickVendel** [comment]
As far as i can tell, this is just the issue of not replacing core.index, so i'll close this issue for now, if issue shows up again, we can open it back up.
