### ISSUE TITLE
[TCOE] 6 Optional Class Features Not Working

### ISSUE THREAD

**Issue by fenixdown83** [AuroraLegacy/elements#66]
It seems as if Optional features in TCOE that replace other class features utilizing the following call "**ID_INTERNAL_FEATURE_REPLACEMENT_**" are broken. In looking for these calls in the **optional-class-features.xml**, there appears to only be 6 of these entries (5 for the Ranger and one for the Cleric).

See images below
![image](https://user-images.githubusercontent.com/10186987/110727038-2185b400-81e0-11eb-9aa5-bb32e9a05173.png)

![image](https://user-images.githubusercontent.com/10186987/110727209-6b6e9a00-81e0-11eb-91d9-eae905995ad3.png)

I confirmed the character I was equipping this item on was a Cleric with the **Divine Strike** feature.
I also tried this on a Ranger with the **Favored Enemy** feature and was trying to replace it with the **Ranger, LV01: Favored Foe** and received a similar error.

**Comment by kgirtxd** [comment]
Thank you for the screenshots. 

It looks like you are not using our core.index, there are parts of the core classes that were changed to make these features work.

**Comment by fenixdown83** [comment]
I just came here to delete this as I had just realized this hahaha

Great work on maintaining these books <3
