### ISSUE TITLE
Homunculus Servant

### ISSUE THREAD

**Issue by stgreenb** [AuroraLegacy/elements#78]
I would like to add Homunculus Servent to the list of companions. I haven't written any code for y'all and I suspect there are some convention errors in here, so rather than making a pull request, I figured I'd just submit what I *THINK* the code should be. I put the book as ERftLW, but the stats are really the updated ones from TCoE (I assume this needs to be duplicated). 

`<element name="Homunculus Servant" type="Companion" source="Eberron: Rising from the Last War" id="ID_WOTC_ERLW_COMPANION_ARTIFICER_HOMUNCULUS_SERVANT ">
		<supports>Homunculus Servant</supports>
		<description>
			<p>You learn intricate methods for magically creating a special homunculus that serves you. The item you 
infuse (A gem or crystal worth at least 100 gp ) serves as the creature's heart, around which the creature's body instantly forms. </p>
			<p><b>Proficiency Bonus (PB)</b> equals your bonus</p>
		</description>
		<setters>
			<set name="strength">4</set>
			<set name="dexterity">15</set>
			<set name="constitution">12</set>
			<set name="intelligence">10</set>
			<set name="wisdom">10</set>
			<set name="charisma">7</set>
			<set name="ac">13 (natural armor)</set>
			<set name="hp">1 + your Intelligence modifier + your artificer level (the Homunculus has a number of Hit Dice [d4s] equal to your artificer level)</set>
			<set name="speed">20 ft., fly 30 ft.</set>
			<set name="immunities">poison</set>
			<set name="conditionImmunities">exhaustion, poisoned</set>			
			<set name="saves">Dex +2 plus PB</set>
			<set name="skills">Perception +0 plus PB x 2, Stealth +2 plus PB </set>
			<set name="senses">darkvision 60 ft., passive Perception 10 + (PB x 2) </set>
			<set name="languages">understands the languages you speak</set>
			<set name="type">Construct</set>
			<set name="size">Tiny</set>
			<set name="alignment">neutral</set>
			<set name="challenge">-</set>
			<set name="traits">ID_WOTC_ERLW_COMPANION_TRAIT_HOMUNCULUS_SERVANT_EVASION</set>
			<set name="actions">ID_WOTC_ERLW_COMPANION_ACTION_HOMUNCULUS_SERVANT_FORCE_STRIKE</set>
			<set name="reactions">ID_WOTC_ERLW_COMPANION_REACTION_HOMUNCULUS_SERVANT_CHANNEL_MAGIC</set>
		</setters>
		<rules>
			<stat name="companion:ac" value="13" bonus="base" />
			<stat name="companion:hp:max" value="1" />
			<stat name="companion:hp:max" value="intelligence:modifier" />
			<stat name="companion:hp:max" value="level:artificer" />
			<stat name="companion:speed" value="20" bonus="base" />
                       <stat name="companion:speed:fly" value="40" bonus="base" />	
			<stat name="companion:proficiency" value="proficiency" bonus="base" />
			<stat name="companion:proficiency" value="-2" bonus="base companion PB removal"/>
			<stat name="companion:stealths:proficiency" value="companion:proficiency" bonus="proficiency" />
			<stat name="companion:perception:proficiency" value="companion:proficiency" bonus="proficiency" />
			<stat name="companion:perception:proficiency" value="companion:proficiency" bonus="double" />
			<stat name="companion:dexterity:save:proficiency" value="companion:proficiency" bonus="proficiency" />
		</rules>
	</element>
	<element name="Evasion" type="Companion Trait" source="Eberron: Rising from the Last War" id="ID_WOTC_ERLW_COMPANION_TRAIT_HOMUNCULUS_SERVANT_EVASION">
		<description>
			<p>If the homunculus is subjected to an effect that allows it to make a Dexterity saving throw to take only half damage, it instead takes no damage if it succeeds on the saving throw, and only half damage if it fails. It can't use this trait if it's incapacitated. </p>
		</description>
		<sheet>
			<description>If the homunculus is subjected to an effect that allows it to make a Dexterity saving throw to take only half damage, it instead takes no damage if it succeeds on the saving throw, and only half damage if it fails. It can't use this trait if it's incapacitated. </description>
		</sheet>
	</element>
	<element name="Force Strike" type="Companion Action" source="Eberron: Rising from the Last War" id="ID_WOTC_ERLW_COMPANION_ACTION_HOMUNCULUS_SERVANT_FORCE_STRIKE">
		<description>
			<p>Ranged Weapon Attack: your spell attack modifier to hit, range 30 ft., one target you can see. Hit: 1d4 + PB force damage. </p>
		</description>
		<sheet>
			<description>Ranged Weapon Attack: your spell attack modifier to hit, range 30 ft., one target you can see. Hit: 1d4 + PB force damage. </description>
		</sheet>
	</element>
	<element name="Channel Magic" type="Companion Reaction" source="Eberron: Rising from the Last War" id="ID_WOTC_ERLW_COMPANION_REACTION_HOMUNCULUS_SERVANT_CHANNEL_MAGIC">
		<description>
			<p> The homunculus delivers a spell you cast that has a range of touch. The homunculus must be within 120 feet of you. </p>
		</description>
		<sheet>
			<description> The homunculus delivers a spell you cast that has a range of touch. The homunculus must be within 120 feet of you. </description>
		</sheet>
	</element>`

**Comment by stgreenb** [comment]
In case its helpful 
![image](https://user-images.githubusercontent.com/18483964/117475984-ab28d800-af2a-11eb-97c3-858e2a9605ba.png)

**Comment by kgirtxd** [comment]
This is reasonable to add,  I will take a look over the weekend.  One thing to note, there is an app limitation that you can only have 1 companion so it will probably be implemented as a companion option but will not be automatically granted to prevent the app from crashing.
